[platformio]
default_envs = xiao_nrf52840_round

[env:xiao_nrf52840_round]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/SdFat - Adafruit Fork
  leamhein/Seeed_GFX@^2.0.3
  seeed-studio/Seeed Arduino FS@^2.1.3
build_flags =
  -D SERIAL_BAUD=115200
  -I include
  -I $PROJECT_PACKAGES_DIR/framework-arduinoadafruitnrf52/libraries/Adafruit_nRFCrypto/src/nrf_cc310/include

[env:native_protocol]
platform = native
test_build_src = no
build_flags =
  -I lib/protocol
  -I lib/map_lite_core
