// Generated by backend/tools/generate_map_stream_trust.py.
// Public verification keys only. Never place private material here.
import Foundation

extension BikeMapStreamTrustStore {
    nonisolated static let production = BikeMapStreamTrustStore(publicKeysByID: [:])
}
